### ISSUE TITLE
Could i ask how you retrieved all those Preference bool settings

### ISSUE THREAD

**Issue by schroef** [ten-A/Extend_Script_experimentals#4]
I wa wondering how you got all those attribute names for the preferences in the '''preferencesKeeper.jsx''' file
I thought that loop over app and return all items would get them, but i only get 3 items returned.

**Comment by ten-A** [comment]
There is no published information about these propaties, but the header files of the Illustrator SDK may be helpful.

**Comment by schroef** [comment]
Guess going through the docs would help me indeed. I find them a bit hard to understand on how to use certain code setup on how to retrieve them.
